package frc.robot;

public enum RobotSettings {
    ROBOT_2020(
            0.0,
            0.0,
            0.000005,
            0.00002,
            30,
            2048,
            10,
            11.2,
            6,
            5000,
            0.7,
            1,
            0.001,
            0.00003,
            0.0001,
            0.001,
            0.001,
            0.00003,
            0.0001,
            0.001,
            2048,
            0,
            0,
            0,
            0,
            0,
            0.07,
            1,
            11.1,
            7,
            270,
            0,
            0.006,
            0.00001,
            0.001,
            20,
            0.1,
            0.05,
            0,
            0,
            1,
            1,
            0.25,
            0,
            1,
            2
    );


    
    RobotSettings(double DRIVEBASE_P,
             double DRIVEBASE_I,
             double DRIVEBASE_D,
             double DRIVEBASE_F,
             int DRIVE_TIMEOUT_MS,
             int DRIVEBASE_SENSOR_UNITS_PER_ROTATION,
             double MAX_SPEED,
             double MAX_ROTATION,
             double WHEEL_DIAMETER,
             double MAX_MOTOR_SPEED,
             double TURN_SCALE,
             double DRIVE_SCALE,

             double SHOOTER_P,
             double SHOOTER_I,
             double SHOOTER_D,
             double SHOOTER_F,
             double SHOOTER_RECOVERY_P,
             double SHOOTER_RECOVERY_I,
             double SHOOTER_RECOVERY_D,
             double SHOOTER_RECOVERY_F,
             double SHOOTER_SENSOR_UNITS_PER_ROTATION,
             double motorPulleySize,
             double driverPulleySize,
             double CAMERA_HEIGHT,
             double CAMERA_PITCH,
             double TARGET_HEIGHT,

             double XBOX_CONTROLLER_DEADZONE,
             double MOTOR_SPROCKET_SIZE,
             double TURRET_SPROCKET_SIZE,
             double TURRET_GEAR_RATIO,
             double TURRET_MAX_POS,
             double TURRET_MIN_POS,
             double TURRET_P,
             double TURRET_I,
             double TURRET_D,
            // double TURRET_F,
             int SHOOTER_TIMEOUT_MS,
             double AUTON_TOLERANCE,
             double HEADING_P,
             double HEADING_I,
             double HEADING_D,
             double AUTO_SPEED,
             double AUTO_ROTATION_SPEED,
             double triggerSensitivity,
             int XBOX_CONTROLLER_SLOT,
             int FLIGHT_STICK_SLOT,
             int BUTTON_PANEL_SLOT){
        
    }
}
